In [1]:
i = 1
while i<6:
    print(i)
    i+=1

1
2
3
4
5


In [3]:
data = [2,4,6,8,10] #tipe data nya list
sum = 0
i = 0

while i<len(data): #dia akan terus berjalan sepanjang i nya kurang dari i = 5, dia akan tetap true selama kurang dari 5
    sum += data[i]
    i += 1 #setiap looping dia akan bertambah 1 yg disimpan di i

rata_rata = sum/len(data) #jumlah data dibagi banyaknya data
print('rata-rata adalah :', rata_rata)

rata-rata adalah : 6.0


In [4]:
data= [5,12,8,20,7,14,11]
filtered_data = []
i=0

while i<len(data):
    if data[i]>10:
        filtered_data.append (data[i])
    i +=1

print('data yang sudah di filter:', filtered_data)

data yang sudah di filter: [12, 20, 14, 11]


In [5]:
my_list = [1,2,3]
my_list.append(4) #menambahkan elemen 4 ke akhir list
print(my_list)

[1, 2, 3, 4]


In [8]:
my_list = []
n = int(input("Masukkan jumlah angka: "))

for i in range(n): #untuk inputan dalam range jumlah angka
    my_list.append(int(input(f"Masukkan angka ke-{i+1}: ")))
print(my_list)

[1, 2, 3, 4]


In [17]:
my_list = [1,2,3]
my_list.insert(2,4) #menambahkan elemen 4 ke akhir list
print(my_list)

[1, 2, 4, 3]


In [20]:
import array as arr

a=arr.array('i',[1,2,3,4,]) #fungsi i untuk mendefinisikan tipe data integer
print(a)

array('i', [1, 2, 3, 4])


In [21]:
import numpy as np
b = np.array([1,2,3,4,5])
print(b)

[1 2 3 4 5]


In [22]:
import numpy as np
b = np.array([1,'a',3,4,5])
print(b)

['1' 'a' '3' '4' '5']


In [23]:
print(type(b))

<class 'numpy.ndarray'>


In [28]:
import numpy as np
my_array2d = np.array([['a','b','c'],[1,2,3],[4,5,6]])
print(my_array2d)

[['a' 'b' 'c']
 ['1' '2' '3']
 ['4' '5' '6']]


In [26]:
import numpy as np

my_array = np.array([1,2,3,4,5])
print(my_array[4])

5


In [30]:
element = my_array2d[1,2] #1, indeks dari array. sedangkan 2 adalah index data array
#yg dipilih adalah index 1 di matriks yg 123, dan 2 yg dipilih yaitu data
print(element)

3


In [31]:
import numpy as np
array1=np.array([1,2,3])
array2=np.array([4,5,6])

gabungan=np.vstack((array1,array2))

print(gabungan)

[[1 2 3]
 [4 5 6]]


In [32]:
import numpy as np
array1=np.array([1,2,3])
array2=np.array([4,5,6])

gabungan=np.hstack((array1,array2))

print(gabungan)

[1 2 3 4 5 6]


In [34]:
import numpy as np
array1=np.array([1,2,3])
array2=np.array([[4,5,6],[7,8,9]])

gabungan=np.vstack((array1,array2))

print(gabungan)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
import numpy as np
array1=np.array([1,2,3])
array2=np.array([4,5,6])

gabungan=np.concatenate((array1,array2),axis=0)

print(gabungan)

[1 2 3 4 5 6]


In [37]:
sliced_array=gabungan[1:4]
print(sliced_array)

[2 3 4]


In [38]:
sliced_array_belakang=gabungan[-1]
print(sliced_array_belakang)

6


In [39]:
for elem in gabungan:
    print(elem)

1
2
3
4
5
6
